### ISSUE TITLE
steps on preparing snowboard input

### ISSUE THREAD

**Issue by Da5hes** [rssys/snowboard#1]
Hi

first of all thank you for sharing the project publicly!

would it be possible to get the method for generating the required input for snowboard?

specifically how one would generate sequential tests for arbitrary kernel versions and are there any requirements or modifications for the tested kernel?

Thanks!

**Comment by sishuaigong** [comment]
Hello,

Sequential tests can be generated using Syzkaller on arbitrary versions and they don't require any modification to the target kernel.
