### ISSUE TITLE
Generating in-memory representation for sequential input

### ISSUE THREAD

**Issue by xingyiz** [rssys/snowboard#3]
Hello! I'm trying to run Snowboard on sequential inputs generated by Syzkaller. Currently, I have generated the syscall programs and have placed them under the `testsuite/input/program` folder. However, I am unsure how to generate its in-memory representation counterpart in the `testsuite/input/data` folder as there is no documentation on that. 

Running `./run-all.sh` on the newly added programs runs, but SKI says "No program data is fetched" and the PMC files are all empty --- I am assuming that the `.data` file is required. 

Could you let me know how I can generate the `.data` file? Also, is placing the `.data` file in the `testsuite/input/data` folder sufficient for SKI to fetch it? Or do I have to update the VM snapshot to include it? Many thanks for your help! :)

**Comment by sishuaigong** [comment]
Hi,

If you want to extend the testsuite by adding new programs, you may find some code useful.

Once you finished the `setup.sh` script, there should be a file `execprog.go` under the folder `snowboard/testsuite/executor/gopath/src/github.com/google/syzkaller/tools/syz-execprog`. This file originally implemented an executor that takes the syzkaller-generated program as input and executes it, but we modified the executor to convert the program into its binary in-memory representation and dump that to the disk (i.e., the `.data` file).

In the function `execute`, you can find what modifications we have introduced.
```go
func (ctx *Context) execute(pid int, env *ipc.Env, entry *prog.LogEntry) {
	// Limit concurrency window.
	ticket := ctx.gate.Enter()
	defer ctx.gate.Leave(ticket)

	callOpts := ctx.execOpts
	if *flagFaultCall == -1 && entry.Fault {
		newOpts := *ctx.execOpts
		newOpts.Flags |= ipc.FlagInjectFault
		newOpts.FaultCall = entry.FaultCall
		newOpts.FaultNth = entry.FaultNth
		callOpts = &newOpts
	}
	if *flagOutput {
		ctx.logProgram(pid, entry.P, callOpts)
	}
	var progdata []byte
    progdata = make([]byte, 4 << 20)
    progSize, err := entry.P.SerializeForExec(progdata)
	if err != nil {
		fmt.Println("Seirlia  aeerreerr",err.Error())
        os.Exit(2)
	}
    fmt.Printf("==================== Program Data ================\n")
    fmt.Printf("%v %v\n", progdata[:progSize], progSize)
	fmt.Printf("==================== Program Data ================\n")
	//str2 := fmt.Sprintf("%d\n", env.pid)
	//fmt.Printf("pid: %s", str2)
	fileObj,err := os.OpenFile(*flagSave ,os.O_RDWR|os.O_CREATE|os.O_TRUNC,0644)
    if err != nil {
        fmt.Println("Failed to open the file",err.Error())
        os.Exit(2)
    }
	defer fileObj.Close()
    fileObj.Write(progdata[:progSize])
    os.Exit(2)
```

I hope you find this reply helpful.
